name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

env: 
  NAME: test-app # Change this to the name of your page

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: pujux/landing-pages-11ty-poc-base
          ref: main

      - name: Build static site
        uses: addnab/docker-run-action@v3
        with:
          image: puf17640/11ty-poc:latest
          options: -v /home/runner/work/landing-pages-11ty-poc-test-app/landing-pages-11ty-poc-test-app/${{ env.NAME }}:/app
          run: eleventy --output=/app/_site

      - run: ls -la ./${{ env.NAME }}/_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./test-app/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
    